[workspace]
resolver = "3"
members = [
    "crates/zettings-core",
    "crates/zettings-search",
    "crates/zettings-polkit",
    "crates/zettings-backends",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.97"
license = "MIT OR Apache-2.0"
repository = "https://github.com/Zyntrix/Zettings"

[workspace.dependencies]
zettings-core = { path = "crates/zettings-core", version = "0.1.0" }
thiserror = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
async-trait = "0.1"

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
pedantic = { level = "deny", priority = -1 }
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
missing_fields_in_debug = "allow"
multiple_crate_versions = "allow"
